# Path: static/admin/config.yml
backend:
  name: git-gateway # Use the Git Gateway interface for local testing
  branch: master # Branch to update (optional; defaults to master)
display_url: https://bisstox.com
site_url: https://bisstox.com

  ### enable below lines for github integration ###
  # name: github
  # repo: Juan-Jones/geeky-hugo/
media_folder: static/images/uploads
public_folder: images/uploads

#Please run "npx netlify-cms-proxy-server" for local backend
local_backend: true
# /admin/config.yml
publish_mode: editorial_workflow

collections:
  - name: blog # Used in routes, e.g., /admin/collections/blog
    label: Blog
    folder: exampleSite/content/blog
    create: true
    slug: "{{slug}}"
    fields: # The fields for each document, usually in front matter
      - label: Layout
        name: layout
        widget: hidden
      - label: Title
        name: title
        widget: string
      - label: Description
        name: description
        widget: string
      - label: Images
        name: images
        widget: list
        fields:
          - {name: path, label: Image, widget: image}
      - label: Date
        name: date
        widget: datetime
      - label: Categories
        name: categories
        widget: select
        multiple: true
        required: true
        options:
          - ecommmerce
          - entrepreneurship
          - gig economy
          - influencing
          - investing
          - monetizing
          - online business
          - personal finance
          - side hustles
      - label: Tags
        name: tags
        widget: select
        multiple: true
        required: true
        options:
          - additional income
          - betterment
          - business
          - freelancing
          - marketing
          - residual income
          - startup
      - label: Type
        name: type
        widget: select
        options:
          - regular
          - featured
      - label: Draft
        name: draft
        widget: boolean
        default: true
      - label: Slug
        name: slug
        widget: string
      - label: Body
        name: body
        widget: markdown
      - label: SEO Keywords
        name: seoKeywords
        widget: string
